---
# handlers file for install_minidlna
- name: restart minidlna
  service: 
    name: minidlna
    state: restarted
- name: restart firewalld
  service: 
    name: firewalld
    state: restarted    